/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.SQLException;


/**
 *
 * @author Dias_Raihan
 */
public class baru extends javax.swing.JFrame {

    static Connection conn;
    static ResultSet res;
    static Statement state;
    
    public baru() {
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        
        conn = DB.connection;
        state = DB.statement;
    }
    
    public void proses_input(){
        try {
            state.executeUpdate("INSERT INTO data_sewa (tbl_id, tbl_kode_lapangan"
                    + ", tbl_tanggal, tbl_jam, tbl_durasi, tbl_nama, tbl_telepon"
                    + ", tbl_uang_muka, tbl_sisa_pembayaran, tbl_status_pembayaran) VALUES ("
                + "'" + txt_idsewa.getText()+"',"
                +"'"+ cmb_kodelapangan.getSelectedItem()+ "',"
                +"'"+ cmb_tanggal.getSelectedItem()+"-"+cmb_bulan.getSelectedItem()+"-"+cmb_tahun.getSelectedItem()+ "',"
                +"'"+ cmb_waktuawal.getSelectedItem()+"-"+cmb_waktuakhir.getSelectedItem()+ "',"
                + "'" + cmb_durasi.getSelectedItem()+"',"
                + "'" + txt_nama.getText()+"',"
                + "'" + txt_nohp.getText()+"',"
                + "'" + txt_uangmuka.getText()+"',"
                + "'" + txt_sisabayar.getText()+"',"        
                + "'" + cmb_status.getSelectedItem()+ "')");
            
            
            JOptionPane.showMessageDialog(null, "Berhasil Menyimpan Data");
            data_sewa gui = new data_sewa();
            gui.setVisible(true);
            this.dispose(); 
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Perintah Salah : "+e);
        }
    }
    
    public void hitung_input(){
        // Harga Lapangan = Rp. 200.000
        int a= Integer.parseInt((String)cmb_durasi.getSelectedItem());
        int b= Integer.parseInt(txt_uangmuka.getText());
        int c= 200000;
        int d= a*c;
        int Hasil= d-b;
        txt_sisabayar.setText(""+Hasil);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmb_waktuawal = new javax.swing.JComboBox<>();
        cmb_waktuakhir = new javax.swing.JComboBox<>();
        lbl_sampai = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_nohp = new javax.swing.JTextField();
        lbl_perbaruidata = new javax.swing.JLabel();
        txt_uangmuka = new javax.swing.JTextField();
        lbl_idsewa = new javax.swing.JLabel();
        cmb_status = new javax.swing.JComboBox<>();
        lbl_kodelapangan = new javax.swing.JLabel();
        btn_batal = new javax.swing.JButton();
        lbl_tanggalsewa = new javax.swing.JLabel();
        btn_proses = new javax.swing.JButton();
        lbl_jamsewa = new javax.swing.JLabel();
        lbl_nama = new javax.swing.JLabel();
        lbl_nohp = new javax.swing.JLabel();
        lbl_uangmuka = new javax.swing.JLabel();
        lbl_status = new javax.swing.JLabel();
        txt_idsewa = new javax.swing.JTextField();
        cmb_kodelapangan = new javax.swing.JComboBox<>();
        cmb_tanggal = new javax.swing.JComboBox<>();
        cmb_bulan = new javax.swing.JComboBox<>();
        cmb_tahun = new javax.swing.JComboBox<>();
        lbl_durasi = new javax.swing.JLabel();
        cmb_durasi = new javax.swing.JComboBox<>();
        lbl_sisabayar = new javax.swing.JLabel();
        txt_sisabayar = new javax.swing.JTextField();
        btn_hitung = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KIPINDEAS FUTSAL");
        setBackground(new java.awt.Color(255, 204, 255));

        cmb_waktuawal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));
        cmb_waktuawal.setSelectedItem(getJMenuBar());

        cmb_waktuakhir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));
        cmb_waktuakhir.setSelectedItem(getJMenuBar());
        cmb_waktuakhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_waktuakhirActionPerformed(evt);
            }
        });

        lbl_sampai.setText("Sampai");

        lbl_perbaruidata.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        lbl_perbaruidata.setText(" DATA BARU");

        txt_uangmuka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_uangmukaActionPerformed(evt);
            }
        });

        lbl_idsewa.setText("ID Sewa");

        cmb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Lunas", "Sudah Lunas" }));
        cmb_status.setSelectedItem(getJMenuBar());

        lbl_kodelapangan.setText("Kode Lapangan");

        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        lbl_tanggalsewa.setText("Tanggal Sewa");

        btn_proses.setText("Proses");
        btn_proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prosesActionPerformed(evt);
            }
        });

        lbl_jamsewa.setText("Jam Sewa");

        lbl_nama.setText("Nama");

        lbl_nohp.setText("No HP");

        lbl_uangmuka.setText("Uang Muka");

        lbl_status.setText("Status");

        txt_idsewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idsewaActionPerformed(evt);
            }
        });

        cmb_kodelapangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LAP001", "LAP002", "LAP003", "LAP004", "LAP005", " " }));
        cmb_kodelapangan.setSelectedItem(getJMenuBar());

        cmb_tanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cmb_tanggal.setSelectedItem(getJMenuBar());

        cmb_bulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember", " " }));
        cmb_bulan.setSelectedItem(getJMenuBar());

        cmb_tahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        cmb_tahun.setSelectedItem(getJMenuBar());
        cmb_tahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tahunActionPerformed(evt);
            }
        });

        lbl_durasi.setText("Durasi (Jam)");

        cmb_durasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        cmb_durasi.setSelectedItem(getJMenuBar());
        cmb_durasi.setToolTipText("");
        cmb_durasi.setName(""); // NOI18N

        lbl_sisabayar.setText("Sisa Bayar");

        txt_sisabayar.setEditable(false);
        txt_sisabayar.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txt_sisabayarInputMethodTextChanged(evt);
            }
        });
        txt_sisabayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sisabayarActionPerformed(evt);
            }
        });

        btn_hitung.setText("Hitung");
        btn_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_batal)
                        .addGap(18, 18, 18)
                        .addComponent(btn_proses))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_hitung, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_status)
                                .addGap(73, 73, 73)
                                .addComponent(cmb_status, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_idsewa)
                                .addComponent(lbl_kodelapangan)
                                .addComponent(lbl_tanggalsewa)
                                .addComponent(lbl_jamsewa)
                                .addComponent(lbl_nohp)
                                .addComponent(lbl_uangmuka)
                                .addComponent(lbl_nama)
                                .addComponent(lbl_durasi)
                                .addComponent(lbl_sisabayar))
                            .addGap(23, 23, 23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_perbaruidata)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmb_durasi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmb_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmb_bulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmb_tahun, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmb_waktuawal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl_sampai)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmb_waktuakhir, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(cmb_kodelapangan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_idsewa)
                                    .addComponent(txt_nama)
                                    .addComponent(txt_nohp)
                                    .addComponent(txt_uangmuka, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_sisabayar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbl_perbaruidata)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_idsewa)
                    .addComponent(txt_idsewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_kodelapangan)
                    .addComponent(cmb_kodelapangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tanggalsewa)
                    .addComponent(cmb_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_tahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_bulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_jamsewa)
                    .addComponent(cmb_waktuawal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_waktuakhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_sampai))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_durasi)
                    .addComponent(cmb_durasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nama)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nohp))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_uangmuka)
                    .addComponent(txt_uangmuka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_sisabayar)
                            .addComponent(txt_sisabayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_status)
                                .addGap(18, 78, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmb_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_batal)
                                    .addComponent(btn_proses))
                                .addGap(23, 23, 23))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_hitung, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_waktuakhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_waktuakhirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_waktuakhirActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        data_sewa gui = new data_sewa();
        gui.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void txt_idsewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idsewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idsewaActionPerformed

    private void btn_prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prosesActionPerformed
        proses_input();
    }//GEN-LAST:event_btn_prosesActionPerformed

    private void txt_uangmukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_uangmukaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_uangmukaActionPerformed

    private void cmb_tahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_tahunActionPerformed

    private void txt_sisabayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sisabayarActionPerformed
    
    }//GEN-LAST:event_txt_sisabayarActionPerformed

    private void txt_sisabayarInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt_sisabayarInputMethodTextChanged
    
    }//GEN-LAST:event_txt_sisabayarInputMethodTextChanged

    private void btn_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitungActionPerformed
        hitung_input();
    }//GEN-LAST:event_btn_hitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(baru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(baru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(baru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(baru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new baru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_hitung;
    private javax.swing.JButton btn_proses;
    private javax.swing.JComboBox<String> cmb_bulan;
    private javax.swing.JComboBox<String> cmb_durasi;
    private javax.swing.JComboBox<String> cmb_kodelapangan;
    private javax.swing.JComboBox<String> cmb_status;
    private javax.swing.JComboBox<String> cmb_tahun;
    private javax.swing.JComboBox<String> cmb_tanggal;
    private javax.swing.JComboBox<String> cmb_waktuakhir;
    private javax.swing.JComboBox<String> cmb_waktuawal;
    private javax.swing.JLabel lbl_durasi;
    private javax.swing.JLabel lbl_idsewa;
    private javax.swing.JLabel lbl_jamsewa;
    private javax.swing.JLabel lbl_kodelapangan;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JLabel lbl_nohp;
    private javax.swing.JLabel lbl_perbaruidata;
    private javax.swing.JLabel lbl_sampai;
    private javax.swing.JLabel lbl_sisabayar;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JLabel lbl_tanggalsewa;
    private javax.swing.JLabel lbl_uangmuka;
    private javax.swing.JTextField txt_idsewa;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nohp;
    private javax.swing.JTextField txt_sisabayar;
    private javax.swing.JTextField txt_uangmuka;
    // End of variables declaration//GEN-END:variables
}
