/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.PreparedStatement;




/**
 *
 * @author Dias_Raihan
 */
public class pembayaran extends javax.swing.JFrame {

    static Connection conn;
    static ResultSet res;
    static Statement state;
    
    public pembayaran() {
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        
        conn = DB.connection;
        state = DB.statement;
    }
    
    public void bayar() {
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Booking sebelumnya ingin di Bayar ???","Confirmation",JOptionPane.YES_NO_OPTION);
        try {
            String sql="UPDATE data_sewa SET tbl_id=?, tbl_uang_muka=?, tbl_sisa_pembayaran=?, tbl_status_pembayaran=?"
                    + "WHERE tbl_id='"+txt_idlunas.getText()+"'";
            PreparedStatement state = conn.prepareStatement(sql);
            if(ok==0) {
                try {
                    state.setString(1,txt_idlunas.getText());
                    state.setString(2,txt_uangmasukbayar.getText());
                    state.setString(3,txt_sisabayarbayar.getText());
                    state.setString(4, (String) cmb_statusbayar.getSelectedItem());
                    state.executeUpdate();

                    data_sewa ds = new data_sewa();
                    ds.tampil();

                    JOptionPane.showMessageDialog(null,"Update Data Sukses");
                    data_sewa gui = new data_sewa();
                    gui.setVisible(true);
                    this.dispose(); 
                }
                    catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Update Data Gagal");
                    }
            }
        } catch (Exception e){}
    }
    
    public void hitung_bayar(){
        int a= Integer.parseInt(txt_uangmasukbayar.getText());
        int b= Integer.parseInt(txt_sisabayarbayar.getText());
        int Hasil= b-a;
        txt_sisabayarbayar.setText(""+Hasil);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_perbaruidata = new javax.swing.JLabel();
        cmb_statusbayar = new javax.swing.JComboBox<>();
        btn_batal = new javax.swing.JButton();
        btn_bayar = new javax.swing.JButton();
        lbl_uangmuka = new javax.swing.JLabel();
        lbl_status = new javax.swing.JLabel();
        lbl_sisabayar = new javax.swing.JLabel();
        txt_sisabayarbayar = new javax.swing.JTextField();
        btn_hitungbayar = new javax.swing.JButton();
        lbl_uangmasuk = new javax.swing.JLabel();
        txt_uangmasukbayar = new javax.swing.JTextField();
        txt_idlunas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KIPINDEAS FUTSAL");
        setBackground(new java.awt.Color(255, 204, 255));

        lbl_perbaruidata.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        lbl_perbaruidata.setText("PEMBAYARAN");

        cmb_statusbayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Lunas", "Sudah Lunas" }));
        cmb_statusbayar.setSelectedItem(getJMenuBar());

        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        btn_bayar.setText("Bayar");
        btn_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bayarActionPerformed(evt);
            }
        });

        lbl_uangmuka.setText("ID");

        lbl_status.setText("Status");

        lbl_sisabayar.setText("Sisa Bayar");

        txt_sisabayarbayar.setEditable(false);
        txt_sisabayarbayar.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txt_sisabayarbayarInputMethodTextChanged(evt);
            }
        });
        txt_sisabayarbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sisabayarbayarActionPerformed(evt);
            }
        });

        btn_hitungbayar.setText("Hitung");
        btn_hitungbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungbayarActionPerformed(evt);
            }
        });

        lbl_uangmasuk.setText("Uang Masuk");

        txt_uangmasukbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_uangmasukbayarActionPerformed(evt);
            }
        });

        txt_idlunas.setEditable(false);
        txt_idlunas.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_uangmuka)
                            .addComponent(lbl_sisabayar)
                            .addComponent(lbl_uangmasuk))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_uangmasukbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txt_sisabayarbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(92, 92, 92)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_perbaruidata)
                                    .addComponent(txt_idlunas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(121, 121, 121))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_hitungbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl_status)
                            .addGap(73, 73, 73)
                            .addComponent(cmb_statusbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_batal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_bayar))))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbl_perbaruidata)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_uangmuka)
                    .addComponent(txt_idlunas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_uangmasuk)
                    .addComponent(txt_uangmasukbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_sisabayar)
                            .addComponent(txt_sisabayarbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_status)
                                .addGap(56, 56, 56))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmb_statusbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_batal)
                                    .addComponent(btn_bayar)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_hitungbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        data_sewa gui = new data_sewa();
        gui.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bayarActionPerformed
        bayar();
    }//GEN-LAST:event_btn_bayarActionPerformed

    private void txt_sisabayarbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sisabayarbayarActionPerformed
    
    }//GEN-LAST:event_txt_sisabayarbayarActionPerformed

    private void txt_sisabayarbayarInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt_sisabayarbayarInputMethodTextChanged
    
    }//GEN-LAST:event_txt_sisabayarbayarInputMethodTextChanged

    private void btn_hitungbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitungbayarActionPerformed
        hitung_bayar();
    }//GEN-LAST:event_btn_hitungbayarActionPerformed

    private void txt_uangmasukbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_uangmasukbayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_uangmasukbayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(baru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(baru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(baru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(baru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new baru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_bayar;
    private javax.swing.JButton btn_hitungbayar;
    public javax.swing.JComboBox<String> cmb_statusbayar;
    private javax.swing.JLabel lbl_perbaruidata;
    private javax.swing.JLabel lbl_sisabayar;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JLabel lbl_uangmasuk;
    private javax.swing.JLabel lbl_uangmuka;
    public javax.swing.JTextField txt_idlunas;
    public javax.swing.JTextField txt_sisabayarbayar;
    public javax.swing.JTextField txt_uangmasukbayar;
    // End of variables declaration//GEN-END:variables
}
