/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.PreparedStatement;




/**
 *
 * @author Dias_Raihan
 */
public class perbarui extends javax.swing.JFrame {

    static Connection conn;
    static ResultSet res;
    static Statement state;
    
    public perbarui() {
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        
        conn = DB.connection;
        state = DB.statement;
    }
    
    public void edit() {
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Untuk Update Record ini???","Confirmation",JOptionPane.YES_NO_OPTION);
        try {
            String sql="update data_sewa set tbl_id=?,tbl_kode_lapangan=?,tbl_tanggal=?,tbl_jam=?,tbl_durasi=?,tbl_nama=?"
                    + ",tbl_telepon=?,tbl_uang_muka=?,tbl_sisa_pembayaran=?,tbl_status_pembayaran=? "
                    + "where tbl_id='"+txt_idsewadb.getText()+"'";
            PreparedStatement state = conn.prepareStatement(sql);
            if(ok==0) {
                try {
                    state.setString(1,txt_idsewadb.getText());
                    state.setString(2, (String) cmb_kodelapangandb.getSelectedItem());
                    state.setString(3,txt_tanggaldb.getText());
                    state.setString(4,txt_jamdb.getText());
                    state.setString(5,(String) cmb_durasidb.getSelectedItem());
                    state.setString(6,txt_namadb.getText());
                    state.setString(7,txt_nohpdb.getText());
                    state.setString(8,txt_uangmukadb.getText());
                    state.setString(9,txt_sisabayardb.getText());
                    state.setString(10, (String) cmb_statusdb.getSelectedItem());
                    state.executeUpdate();

                    data_sewa ds = new data_sewa();
                    ds.tampil();

                    JOptionPane.showMessageDialog(null,"Update Data Sukses");
                    data_sewa gui = new data_sewa();
                    gui.setVisible(true);
                    this.dispose(); 
                }
                    catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Update Data Gagal");
                    }
            }
        } catch (Exception e){}
    }
    
    public void hitung_edit(){
        // Harga Lapangan = Rp. 200.000
        int a= Integer.parseInt((String)cmb_durasidb.getSelectedItem());
        int b= Integer.parseInt(txt_uangmukadb.getText());
        int c= 200000;
        int d= a*c;
        int Hasil= d-b;
        txt_sisabayardb.setText(""+Hasil);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_namadb = new javax.swing.JTextField();
        txt_nohpdb = new javax.swing.JTextField();
        lbl_perbaruidata = new javax.swing.JLabel();
        txt_uangmukadb = new javax.swing.JTextField();
        lbl_idsewadb = new javax.swing.JLabel();
        cmb_statusdb = new javax.swing.JComboBox<>();
        lbl_kodelapangandb = new javax.swing.JLabel();
        btn_batal = new javax.swing.JButton();
        lbl_tanggalsewadb = new javax.swing.JLabel();
        btn_perbarui = new javax.swing.JButton();
        lbl_jamsewa = new javax.swing.JLabel();
        lbl_nama = new javax.swing.JLabel();
        lbl_nohp = new javax.swing.JLabel();
        lbl_uangmuka = new javax.swing.JLabel();
        lbl_status = new javax.swing.JLabel();
        txt_idsewadb = new javax.swing.JTextField();
        cmb_kodelapangandb = new javax.swing.JComboBox<>();
        lbl_durasi = new javax.swing.JLabel();
        cmb_durasidb = new javax.swing.JComboBox<>();
        lbl_sisabayar = new javax.swing.JLabel();
        txt_sisabayardb = new javax.swing.JTextField();
        btn_hitungdb = new javax.swing.JButton();
        txt_tanggaldb = new javax.swing.JTextField();
        txt_jamdb = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KIPINDEAS FUTSAL");
        setBackground(new java.awt.Color(255, 204, 255));

        lbl_perbaruidata.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        lbl_perbaruidata.setText(" PEMBARUAN DATA");

        txt_uangmukadb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_uangmukadbActionPerformed(evt);
            }
        });

        lbl_idsewadb.setText("ID Sewa");

        cmb_statusdb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Lunas", "Sudah Lunas" }));
        cmb_statusdb.setSelectedItem(getJMenuBar());

        lbl_kodelapangandb.setText("Kode Lapangan");

        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        lbl_tanggalsewadb.setText("Tanggal Sewa");

        btn_perbarui.setText("Perbarui");
        btn_perbarui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_perbaruiActionPerformed(evt);
            }
        });

        lbl_jamsewa.setText("Jam Sewa");

        lbl_nama.setText("Nama");

        lbl_nohp.setText("No HP");

        lbl_uangmuka.setText("Uang Muka");

        lbl_status.setText("Status");

        txt_idsewadb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idsewadbActionPerformed(evt);
            }
        });

        cmb_kodelapangandb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LAP001", "LAP002", "LAP003", "LAP004", "LAP005", " " }));
        cmb_kodelapangandb.setSelectedItem(getJMenuBar());

        lbl_durasi.setText("Durasi (Jam)");

        cmb_durasidb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        cmb_durasidb.setSelectedItem(getJMenuBar());
        cmb_durasidb.setToolTipText("");
        cmb_durasidb.setName(""); // NOI18N

        lbl_sisabayar.setText("Sisa Bayar");

        txt_sisabayardb.setEditable(false);
        txt_sisabayardb.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txt_sisabayardbInputMethodTextChanged(evt);
            }
        });
        txt_sisabayardb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sisabayardbActionPerformed(evt);
            }
        });

        btn_hitungdb.setText("Hitung");
        btn_hitungdb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungdbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn_hitungdb, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_status)
                                    .addGap(73, 73, 73)
                                    .addComponent(cmb_statusdb, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_batal)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_perbarui)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_idsewadb)
                                    .addComponent(lbl_kodelapangandb)
                                    .addComponent(lbl_tanggalsewadb)
                                    .addComponent(lbl_jamsewa)
                                    .addComponent(lbl_nohp)
                                    .addComponent(lbl_uangmuka)
                                    .addComponent(lbl_nama)
                                    .addComponent(lbl_durasi)
                                    .addComponent(lbl_sisabayar))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmb_durasidb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmb_kodelapangandb, 0, 233, Short.MAX_VALUE)
                                    .addComponent(txt_namadb)
                                    .addComponent(txt_nohpdb)
                                    .addComponent(txt_uangmukadb, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_sisabayardb, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_idsewadb)
                                    .addComponent(txt_tanggaldb)
                                    .addComponent(txt_jamdb)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(lbl_perbaruidata)))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbl_perbaruidata)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_idsewadb)
                    .addComponent(txt_idsewadb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_kodelapangandb)
                    .addComponent(cmb_kodelapangandb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tanggalsewadb)
                    .addComponent(txt_tanggaldb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_jamsewa)
                    .addComponent(txt_jamdb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_durasi)
                    .addComponent(cmb_durasidb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nama)
                    .addComponent(txt_namadb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nohpdb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nohp))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_uangmuka)
                    .addComponent(txt_uangmukadb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_sisabayar)
                            .addComponent(txt_sisabayardb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_status)
                                .addGap(18, 86, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmb_statusdb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_batal)
                                    .addComponent(btn_perbarui))
                                .addGap(23, 23, 23))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_hitungdb, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        data_sewa gui = new data_sewa();
        gui.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void txt_idsewadbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idsewadbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idsewadbActionPerformed

    private void btn_perbaruiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_perbaruiActionPerformed
        edit();
    }//GEN-LAST:event_btn_perbaruiActionPerformed

    private void txt_uangmukadbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_uangmukadbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_uangmukadbActionPerformed

    private void txt_sisabayardbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sisabayardbActionPerformed
    
    }//GEN-LAST:event_txt_sisabayardbActionPerformed

    private void txt_sisabayardbInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt_sisabayardbInputMethodTextChanged
    
    }//GEN-LAST:event_txt_sisabayardbInputMethodTextChanged

    private void btn_hitungdbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitungdbActionPerformed
        hitung_edit();
    }//GEN-LAST:event_btn_hitungdbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(baru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(baru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(baru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(baru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new baru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_hitungdb;
    private javax.swing.JButton btn_perbarui;
    public javax.swing.JComboBox<String> cmb_durasidb;
    public javax.swing.JComboBox<String> cmb_kodelapangandb;
    public javax.swing.JComboBox<String> cmb_statusdb;
    private javax.swing.JLabel lbl_durasi;
    private javax.swing.JLabel lbl_idsewadb;
    private javax.swing.JLabel lbl_jamsewa;
    private javax.swing.JLabel lbl_kodelapangandb;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JLabel lbl_nohp;
    private javax.swing.JLabel lbl_perbaruidata;
    private javax.swing.JLabel lbl_sisabayar;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JLabel lbl_tanggalsewadb;
    private javax.swing.JLabel lbl_uangmuka;
    public javax.swing.JTextField txt_idsewadb;
    public javax.swing.JTextField txt_jamdb;
    public javax.swing.JTextField txt_namadb;
    public javax.swing.JTextField txt_nohpdb;
    public javax.swing.JTextField txt_sisabayardb;
    public javax.swing.JTextField txt_tanggaldb;
    public javax.swing.JTextField txt_uangmukadb;
    // End of variables declaration//GEN-END:variables
}
